import { join } from "path";
import { createInterface } from "readline";
import { ensureDir, writeText, writeJson, fileExists } from "@relic/utility";
import { nextSpecId, slugify } from "@relic/utility";
import { TEMPLATES } from "../generated/templates.ts";
import { buildContext, renderContext } from "../core/context-builder.ts";
import { runModel } from "../core/model-runner.ts";

export interface SpecifyOptions {
  title?: string;
  relicDir: string;
  noStream?: boolean;
  resetContext?: boolean;
}

function ask(question: string): Promise<string> {
  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

export async function runSpecify(options: SpecifyOptions): Promise<void> {
  let title = options.title?.trim();
  if (!title) {
    title = await ask("Spec title: ");
    if (!title) {
      console.error("Error: title is required.");
      process.exit(1);
    }
  }

  const slug = slugify(title);
  const specsDir = join(options.relicDir, "specs");
  const specId = nextSpecId(specsDir, slug);
  const specDir = join(specsDir, specId);
  const date = new Date().toISOString().slice(0, 10);

  ensureDir(specDir);

  const replace = (template: string) =>
    template
      .replace(/\{\{TITLE\}\}/g, title!)
      .replace(/\{\{SPEC_ID\}\}/g, specId)
      .replace(/\{\{DATE\}\}/g, date);

  writeText(join(specDir, "spec.md"), replace(TEMPLATES["spec.md"] ?? ""));
  writeText(join(specDir, "plan.md"), replace(TEMPLATES["plan.md"] ?? ""));
  writeText(join(specDir, "tasks.md"), replace(TEMPLATES["tasks.md"] ?? ""));
  writeJson(join(specDir, "artifacts.json"), {
    owns: [],
    reads: [],
    touches_files: [],
  });

  console.log(`Spec created: .relic/specs/${specId}/`);
  console.log("");
  console.log("Files:");
  console.log("  spec.md       — fill in your requirements");
  console.log("  plan.md       — generated by /relic.plan");
  console.log("  tasks.md      — generated by /relic.tasks");
  console.log("  artifacts.json — declare owned and read artifacts");
  console.log("");

  const ctx = buildContext(options.relicDir, specId);
  const renderedContext = renderContext(ctx);
  const userMessage = title
    ? renderedContext + `\n\n## Title\n\n${title}`
    : renderedContext;
  await runModel({
    command: "specify",
    userMessage,
    relicDir: options.relicDir,
    specId,
    noStream: options.noStream,
    resetContext: options.resetContext,
  });
}
