#!/usr/bin/env bun
/**
 * Prebuild script: reads all markdown files under templates/prompts/ and generates
 * packages/engines/src/generated/engine-templates.ts as an exported string map.
 *
 * Run before compilation: bun run scripts/embed-engine-templates.ts
 */

import { readdirSync, readFileSync, statSync, mkdirSync, writeFileSync } from "fs";
import { join, relative } from "path";

const ROOT = join(import.meta.dir, "..");
const PROMPTS_DIR = join(ROOT, "templates", "prompts");
const OUT_FILE = join(ROOT, "packages/engines/src/generated/engine-templates.ts");

function collectFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...collectFiles(full));
    } else if (entry.endsWith(".md")) {
      results.push(full);
    }
  }
  return results;
}

const files = collectFiles(PROMPTS_DIR);
const entries: string[] = [];

for (const file of files) {
  const rel = relative(join(ROOT, "templates"), file).replace(/\\/g, "/");
  const content = readFileSync(file, "utf8");
  const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  entries.push(`  ${JSON.stringify(rel)}: \`${escaped}\``);
}

const output = `// Auto-generated by scripts/embed-engine-templates.ts — do not edit manually.
// Source of truth: templates/prompts/*.md
export const ENGINE_TEMPLATES: Record<string, string> = {
${entries.join(",\n")},
};
`;

mkdirSync(join(ROOT, "packages/engines/src/generated"), { recursive: true });
writeFileSync(OUT_FILE, output, "utf8");

console.log(`Embedded ${files.length} engine templates → packages/engines/src/generated/engine-templates.ts`);
