#!/usr/bin/env bun
/**
 * Prebuild script: reads all markdown files under templates/ and generates
 * packages/core/src/generated/templates.ts as exported string constants.
 *
 * Run before compilation: bun run scripts/embed-templates.ts
 */

import { readdirSync, readFileSync, statSync, mkdirSync, writeFileSync } from "fs";
import { join, relative } from "path";

const ROOT = join(import.meta.dir, "..");
const TEMPLATES_DIR = join(ROOT, "templates");
const OUT_FILE = join(ROOT, "packages/core/src/generated/templates.ts");

const PROMPTS_DIR = join(TEMPLATES_DIR, "prompts");

function collectFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      // prompts/ are owned by embed-engine-templates.ts
      if (full === PROMPTS_DIR) continue;
      results.push(...collectFiles(full));
    } else if (entry.endsWith(".md") || entry.endsWith(".sh")) {
      results.push(full);
    }
  }
  return results;
}

const files = collectFiles(TEMPLATES_DIR);
const entries: string[] = [];

for (const file of files) {
  const key = relative(TEMPLATES_DIR, file).replace(/\\/g, "/");
  const content = readFileSync(file, "utf8");
  // Escape backticks and template literal syntax in content
  const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  entries.push(`  ${JSON.stringify(key)}: \`${escaped}\``);
}

const output = `// Auto-generated by scripts/embed-templates.ts — do not edit manually.
// Source of truth: templates/**/*.md and templates/**/*.sh
export const TEMPLATES: Record<string, string> = {
${entries.join(",\n")},
};
`;

mkdirSync(join(ROOT, "packages/core/src/generated"), { recursive: true });
writeFileSync(OUT_FILE, output, "utf8");

console.log(`Embedded ${files.length} templates → packages/core/src/generated/templates.ts`);
